import { contextBridge, ipcRenderer } from 'electron'

const RUN_CODE_CHANNEL = 'quest:run-code'
const STUB_CHANNEL = 'quest:stub'

/**
 * Bridge between the renderer and the main process. Every function here is a deliberate
 * decision: this is the only surface between the game and the system (ADR 0008).
 */
export const api = {
  /** Runs the player's code and comes back with the harness envelope (ADR 0009). */
  runCode(request: unknown): Promise<unknown> {
    return ipcRenderer.invoke(RUN_CODE_CHANNEL, request)
  },

  /** The starting code for a challenge, generated by the language adapter (ADR 0005). */
  stubFor(request: unknown): Promise<unknown> {
    return ipcRenderer.invoke(STUB_CHANNEL, request)
  },
}

contextBridge.exposeInMainWorld('api', api)
