import { contextBridge, ipcRenderer } from 'electron'

const RUN_CODE_CHANNEL = 'quest:run-code'
const STUB_CHANNEL = 'quest:stub'
const LSP_START_CHANNEL = 'lsp:start'
const LSP_SEND_CHANNEL = 'lsp:send'
const LSP_STOP_CHANNEL = 'lsp:stop'
const LSP_MESSAGE_EVENT = 'lsp:message'

/**
 * Bridge between the renderer and the main process. Every function here is a deliberate
 * decision: this is the only surface between the game and the system (ADR 0008).
 */
export const api = {
  /** Runs the player's code and comes back with the harness envelope (ADR 0009). */
  runCode(request: unknown): Promise<unknown> {
    return ipcRenderer.invoke(RUN_CODE_CHANNEL, request)
  },

  /** The starting code for a challenge, generated by the language adapter (ADR 0005). */
  stubFor(request: unknown): Promise<unknown> {
    return ipcRenderer.invoke(STUB_CHANNEL, request)
  },

  /** Starts the language server for a language, when it has one (ADR 0044). */
  startLanguageServer(request: unknown): Promise<unknown> {
    return ipcRenderer.invoke(LSP_START_CHANNEL, request)
  },

  /** Sends one JSON-RPC message to a language server. */
  sendToLanguageServer(payload: unknown): void {
    ipcRenderer.send(LSP_SEND_CHANNEL, payload)
  },

  /**
   * Subscribes to everything the language servers say. Only the payload crosses over: the
   * IPC event itself stays on this side of the bridge.
   */
  onLanguageServerMessage(listener: (payload: unknown) => void): void {
    ipcRenderer.on(LSP_MESSAGE_EVENT, (_event, payload: unknown) => {
      listener(payload)
    })
  },

  stopLanguageServers(): void {
    ipcRenderer.send(LSP_STOP_CHANNEL)
  },
}

contextBridge.exposeInMainWorld('api', api)
