import type { Challenge, LanguageId, RunRequest } from '@unifor-quest/core'
import { type RunEnvelope, runEnvelopeSchema } from '@unifor-quest/core'

/**
 * Whatever comes back over IPC is untrusted until it has been through the schema
 * (ADR 0017), even though the sender is our own main process.
 */
/** The starting code the player sees, generated by the adapter in the main process. */
export async function stubFor(challenge: Challenge, language: LanguageId): Promise<string> {
  const raw = await window.api.stubFor({ challenge, language })
  return typeof raw === 'string' ? raw : ''
}

export async function runCode(request: RunRequest): Promise<RunEnvelope> {
  const raw = await window.api.runCode(request)
  const parsed = runEnvelopeSchema.safeParse(raw)

  if (!parsed.success) {
    return { results: [], playerStdout: '', error: 'O resultado da execucao veio corrompido.' }
  }

  return parsed.data
}
